### ISSUE TITLE
No longer works for /ifr/ links and reddit previews

### ISSUE THREAD

**Issue by 8ars1** [Invertex/RedGifs-AutoHD#16]
Hi, the script no longer seems to work for redgifs.com/ifr/... links as well as the reddit preview expansions (as was mentioned in the most recent issue).

**Comment by Invertex** [comment]
It does work, in terms of video quality. It just isn't changing what the icon looks like. But I'll try and fix that.

**Comment by Invertex** [comment]
Should be fixed now

**Comment by 8ars1** [comment]
Hi, thanks for the quick reply. I'm actually still getting the same issue
(in both cases). Also, are you sure they're the same quality? When I right
click -> view video, I get "-mobile-" in the url of the sd version but not
in the hd version, which is what used to be the case before I downloaded
the script.

**Comment by 8ars1** [comment]
I'm using Firefox as well actually. I also just checked on Chrome and I
have the issue there as well.

**Comment by 8ars1** [comment]
Oh, that was it. Sorry about that. Works perfectly now, thanks.
